language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without tools
script:
  - bundle exec rake
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.10.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
addons:
  code_climate:
    repo_token: 029b5aa100b82b6710e285597b7eabe760357b5dd1f626514371356055378d8c
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
