language: ruby
dist: trusty
sudo: false
cache: bundler
bundler_args: --without console
script:
  - bundle exec rake spec
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - jruby-9.1.5.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
addons:
  code_climate:
    repo_token: 029b5aa100b82b6710e285597b7eabe760357b5dd1f626514371356055378d8c
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
